# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c33f9d903ad1b59c077a09e20136fa45b612795bf1be0ce93123be7ab56113d094047f7bcc3cdc6e7527c811a2f322505ebbb41e230ddfc84a3312560f36856c

test:
  secret_key_base: 5e4bbe266b73585d109f996e1067840628e72c37a1c108967a9edcbc4c3dda8399d6fbd831fe8adbe4c3ae2afeef3f7bee02f760bb8613966c4557206b8549c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
